#!/bin/bash
echo "--- Notice ------------------------------------------------------"
echo "-                                                               -"
echo "-  This command has been disabled by the system administrator.  -"
echo "-  Please use the control panel to setup a website.             -"
echo "-                                                               -"
echo "-----------------------------------------------------------------"
