#!/bin/bash
if [ -z "$1" ]; then
echo "Usage: /sbin/changepassword username password"
else
if [ -z "$2" ]; then
echo "Usage: /sbin/changepassword username password"
else
passwd $1 <<EOF
$2
$2
EOF
echo "Password changed successfully!"
fi
fi
